improve release contrib script

diff --git a/contrib/make-bin-dist b/contrib/make-bin-dist
--- a/contrib/make-bin-dist
+++ b/contrib/make-bin-dist
@@ -2,20 +2,59 @@
 #
 # A very cheesy script to prep a release
 #
+set -e
+
+platform() {
+  case `uname` in
+    Darwin) echo 'osx' ;;
+    Linux) echo 'linux' ;;
+    FreeBSD) echo 'freebsd' ;;
+    *) echo 'unknown' ;;
+  esac
+}
+
+
+arch() {
+  case "$1" in
+    osx|freebsd|linux)
+      if file bin/tripwire | grep -q '64-bit'; then
+        echo 'x86_64'
+      else
+        echo 'x86'
+      fi
+      ;;
+    *) echo 'unknown'
+  esac
+}
+
 
 PRODUCT=tripwire
 VERSION=2.4.2.2
-ARCH=x86
+PLATFORM=`platform`
+ARCH=`arch $PLATFORM`
 TYPE=bin
-ROOT_DIR=$PRODUCT-$VERSION-$ARCH-$TYPE
+ROOT_DIR=$PRODUCT-$VERSION-$PLATFORM-$ARCH-$TYPE
 EXCLUDES='.svn .git .gitignore'
+EXCLUDES="$(for EXCLUDE in $EXCLUDES; do echo --exclude $EXCLUDE; done)"
 
-mkdir $ROOT_DIR
+SCRIPT_DIR="$(cd `dirname $0`; pwd)"
+SCRIPT_DIR_DOTDOT="$(dirname "$SCRIPT_DIR")"
+
+if ! test -x bin/tripwire* ; then
+  echo "tripwire not ready for release (bins not found in bin/ dir)" >&2
+  exit 1
+fi
+
+trap 'RESULT=$?; rm -rf "$SCRIPT_DIR_DOTDOT/releases/$ROOT_DIR"; exit $RESULT' INT QUIT EXIT TERM ERR
+
+mkdir -p "$SCRIPT_DIR_DOTDOT/releases"
+cd "$SCRIPT_DIR_DOTDOT/releases"
+mkdir "$ROOT_DIR"
 ln -s ../bin ../contrib ../man ../policy $ROOT_DIR/
-ln -s ../COPYING ../ChangeLog ../INSTALL ../MAINTAINERS $ROOT_DIR/
+ln -s ../COPYING ../ChangeLog ../MAINTAINERS $ROOT_DIR/
 ln -s ../TRADEMARK ../COMMERCIAL ../install ../install-sh $ROOT_DIR/
 
-EXTENSIONS=(.tar.bz2 .tar.gz .tar.xz)
+EXTENSIONS=(tar.bz2 tar.gz tar.xz)
 TAR_OPTIONS=(j z J)
 
 sha1() {
@@ -27,7 +66,12 @@ sha512() {
 }
 
 sign() {
-  gpg --detach-sign --output "$1.asc" "$1"
+  if which gpg >/dev/null 2>&1; then
+    gpg --detach-sign --output "$1.asc" "$1"
+  else
+    echo "gpg unavailable, release is unsigned !!" >&2
+    exit 1
+  fi
 }
 
 for INDEX in 1 2 3; do
@@ -35,7 +79,7 @@ for INDEX in 1 2 3; do
   TAR_OPTIONS="${TAR_OPTIONS[$INDEX]}"
   TARBALL="$ROOT_DIR.${EXTENSION}"
 
-  tar ${TAR_OPTIONS}hcf $TARBALL $ROOT_DIR --exclude $EXCLUDES
+  tar $EXCLUDES -${TAR_OPTIONS}hcf $TARBALL $ROOT_DIR
 
   sha1 $TARBALL > $ROOT_DIR.sha1
   sha1 bin/* >> $ROOT_DIR.sha1
